Attempt at bugfix: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer] 	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:108) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructDefaultTuplizer(EntityTuplizerFactory.java:133) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.tuple.entity.EntityEntityModeToTuplizerMapping.&lt;init&gt;(EntityEntityModeToTuplizerMapping.java:80) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.tuple.entity.EntityMetamodel.&lt;init&gt;(EntityMetamodel.java:322) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.persister.entity.AbstractEntityPersister.&lt;init&gt;(AbstractEntityPersister.java:473) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.persister.entity.SingleTableEntityPersister.&lt;init&gt;(SingleTableEntityPersister.java:133) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.persister.PersisterFactory.createClassPersister(PersisterFactory.java:84) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.impl.SessionFactoryImpl.&lt;init&gt;(SessionFactoryImpl.java:284) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1842) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at at.silverstrike.pcc.impl.persistence.DefaultPersistence.tryToOpenSession(DefaultPersistence.java:760) ~[classes/:na] 	at at.silverstrike.pcc.impl.persistence.DefaultPersistence.openSession(DefaultPersistence.java:591) ~[classes/:na] 	at at.silverstrike.pcc.projectscheduler.TestDefaultProjectScheduler.testRun01(TestDefaultProjectScheduler.java:132) [test-classes/:na] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_23] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_23] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_23] 	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_23] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.8.1.jar:na] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.8.1.jar:na] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.8.1.jar:na] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.8.1.jar:na] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76) [junit-4.8.1.jar:na] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit-4.8.1.jar:na] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193) [junit-4.8.1.jar:na] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52) [junit-4.8.1.jar:na] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191) [junit-4.8.1.jar:na] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42) [junit-4.8.1.jar:na] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184) [junit-4.8.1.jar:na] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236) [junit-4.8.1.jar:na] 	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62) [surefire-junit4-2.4.3.jar:2.4.3] 	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140) [surefire-api-2.4.3.jar:2.4.3] 	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127) [surefire-api-2.4.3.jar:2.4.3] 	at org.apache.maven.surefire.Surefire.run(Surefire.java:177) [surefire-api-2.4.3.jar:2.4.3] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_23] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_23] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_23] 	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_23] 	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:345) [surefire-booter-2.4.3.jar:2.4.3] 	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009) [surefire-booter-2.4.3.jar:2.4.3] Caused by: java.lang.reflect.InvocationTargetException: null 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_23] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_23] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_23] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_23] 	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:105) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	... 37 common frames omitted Caused by: java.lang.NoClassDefFoundError: javassist/util/proxy/MethodFilter 	at org.hibernate.bytecode.javassist.BytecodeProviderImpl.getProxyFactoryFactory(BytecodeProviderImpl.java:49) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactoryInternal(PojoEntityTuplizer.java:205) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:183) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.tuple.entity.AbstractEntityTuplizer.&lt;init&gt;(AbstractEntityTuplizer.java:167) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	at org.hibernate.tuple.entity.PojoEntityTuplizer.&lt;init&gt;(PojoEntityTuplizer.java:77) ~[hibernate-core-3.6.0.Final.jar:3.6.0.Final] 	... 42 common frames omitted Caused by: java.lang.ClassNotFoundException: javassist.util.proxy.MethodFilter 	at java.net.URLClassLoader$1.run(URLClassLoader.java:202) ~[na:1.6.0_23] 	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.6.0_23] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[na:1.6.0_23] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:307) ~[na:1.6.0_23] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301) ~[na:1.6.0_23] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:248) ~[na:1.6.0_23] 	... 47 common frames omitted